name: ${project.artifactId}
main: ${project.groupId}:${project.artifactId}
author: ${project.developers[0].name}
version: ${project.version}
api-version: 1.13
description: ${project.description}
website: ${project.url}