name: ${project.artifactId}
main: ${project.groupId}.${artifactId.lowercase}.${project.artifactId}
author: OnyxianSoul
version: ${project.version}
api-version: 1.13
description: ${description}
website: ${project.url}