name: PlayerFallEventAPI
main: com.gmail.onyxiansoul.playerfalleventapi.PlayerFallEventAPI
author: OnyxianSoul
version: ${project.version}
api-version: 1.13
description: "A developer API. When installed, it detects player falls, and calls the following event types: PlayerStartFallEvent & PlayerFinishFallEvent"
website: https://www.spigotmc.org/threads/playerfalleventapi.475044/